Homepage
yashodaAgarwal/Ecom-website pull request #1
Opened 2022-02-19 20:25 UTC by yashodaAgarwal

Please review my home, login and signup page

2022-02-19 21:08 UTC, notmafiaa requested changes
Please Check at the comments

2022-02-19 21:08 UTC, notmafiaa commented on Styles/Login.css
> +  box-shadow: 1px 1px 10px var(--black-color);
px values ? any specific reason you have used it? 

use rems instead. If possible!!

2022-02-19 21:08 UTC, notmafiaa commented on Styles/Login.css
> +}
check here too

2022-02-19 21:08 UTC, notmafiaa commented on Styles/Login.css
> +}
check here

2022-02-19 21:08 UTC, notmafiaa commented on Styles/Login.css
> +  padding: 10px;
check

2022-02-19 21:08 UTC, notmafiaa commented on Styles/Login.css
> +}
check

2022-02-19 21:08 UTC, notmafiaa commented on Styles/Login.css
> +}
check

2022-02-19 21:08 UTC, notmafiaa commented on Styles/home.css
> +  text-align: center;
do check!!

2022-02-19 21:08 UTC, notmafiaa commented on Styles/home.css
> +  width: 500px;
do check the values!!

2022-02-20 13:21 UTC, yashodaAgarwal commented on Styles/home.css
> +  width: 500px;
changed

2022-02-20 13:23 UTC, ArpitPatni commented
Use rem or % in place of px (just a suggestion).Otherwise good to merge

2022-02-20 13:25 UTC, merged